compartment_ocid      = "ocid1.tenancy.oc1..aaaaaaaax53vlejj4e56y7uuracylzczzih2itft4z6uqolc4vsgxczmr6xa"
instance_name         = "db23cfree"
existing_instance_id = "ocid1.instance.oc1.iad.anuwcljsftrhhbychtvmq4kvkt5xby7e3siiay5ayhd2mzovwof7bof6dlqa"
region                = "us-ashburn-1"
ssh_public_key_path   = "server.key.pub"
ssh_private_key_path  = "server.key"
